### ISSUE TITLE
Get thumbnail view working

### ISSUE THREAD

**Issue by swandog30** [Minitex/PDFKitTest#1]
- thumbnails horizontally scrollable
- navigation by tapping thumbnails

**Comment by vuinguyen** [comment]
Due to limitations of the PDFThumbnailView class in PDFKit, we will have to roll our own custom thumbnail viewer. For the MVP, the thumbnail viewer will display thumbnails in a grid, similar to a collection view, as this design is the lowest barrier to entry. Also, for this iteration, we won't worry about displaying page numbers. Depending on how difficult it would be to implement for this iteration (and how it may affect the user experience), we may also leave out lazy loading (displaying the thumbnails only when they scroll into view) for now .

**Comment by vuinguyen** [comment]
<img width="242" alt="screen shot 2017-10-10 at 2 59 07 pm" src="https://user-images.githubusercontent.com/1022275/31410443-dba107c8-adcb-11e7-9b79-29d9e0eb03a0.png"><img width="242" alt="screen shot 2017-10-10 at 3 00 16 pm" src="https://user-images.githubusercontent.com/1022275/31410447-dee26e18-adcb-11e7-9c4f-74c9f935d345.png">


Got thumbnails for all the pages to display in the custom thumbnail viewer, and clicking on a thumbnail takes us to that page

**Comment by vuinguyen** [comment]
This feature has been approved to go into Testflight, so will close issue for now.
